## servlet configuration
server:
  servlet:
    context-path: /openfashion-core-service
  port: 5000

## application configuration
spring:
  application:
    name: openfashion-core-service
  datasource:
    url: jdbc:mysql://open-fashion-db-instance.cf3zfdqdzdpj.us-east-1.rds.amazonaws.com:3306/openfashion_core?createDatabaseIfNotExist=true
    username: admin
    password: nawaz_admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: admin
    password: nawaz_admin
    baseline-version: 0
    baseline-description: "init db migration"


## oauth2 security configuration
security:
  oauth2:
    resource:
      token-info-uri: http://openfashionbackend-env.eba-4xyfbd5x.us-east-1.elasticbeanstalk.com/openfashion-auth-service/oauth/check_token
    client:
      client-id: open_fashion_mobile
      client-secret: 3615

# oauth2 resource server configuration
oauth:
  resource-id: ${RESOURCE_ID:core_server}

# cors configuration
accessControl:
  allowedOrigin: ${ALLOWED_ORIGIN:*}
  allowedMethods: ${ALLOWED_METHODS:GET, POST, PUT, PATCH, DELETE, OPTIONS}
  maxAge: ${MAX_AGE:3600}
  allowedHeaders: ${ALLOWED_HEADERS:*}
